server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sreenudagumati/userapp-config
          search-paths:
          - "userconfig*"
          
          
          
management:
  security:
    enabled: false