server:
  port: 8888
  context-path: /product
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sreenudagumati/springcloud-config
          search-paths:
          - "myfolder*"
  
management:
  security:
    enabled: false
    